// Code generated by command: go run main.go -out lz77_amd64.s -stubs lz77_stub_amd64.go. DO NOT EDIT.

package deflate

func lz77Asm4kL12V1(base *level1context, input []byte, processed int, offset int, tokens []token, maxToken int) (nOffset int, ntokens []token)

func lz77Asm32kL12V1(base *level1context, input []byte, processed int, offset int, tokens []token, maxToken int) (nOffset int, ntokens []token)

func lz77Asm4kL12V3(base *level1context, input []byte, processed int, offset int, tokens []token, maxToken int) (nOffset int, ntokens []token)

func lz77Asm32kL12V3(base *level1context, input []byte, processed int, offset int, tokens []token, maxToken int) (nOffset int, ntokens []token)

func lz77Asm4kL12V4(base *level1context, input []byte, processed int, offset int, tokens []token, maxToken int) (nOffset int, ntokens []token)

func lz77Asm32kL12V4(base *level1context, input []byte, processed int, offset int, tokens []token, maxToken int) (nOffset int, ntokens []token)

func lz77Asm4kL15V1(base *level2context, input []byte, processed int, offset int, tokens []token, maxToken int) (nOffset int, ntokens []token)

func lz77Asm32kL15V1(base *level2context, input []byte, processed int, offset int, tokens []token, maxToken int) (nOffset int, ntokens []token)

func lz77Asm4kL15V3(base *level2context, input []byte, processed int, offset int, tokens []token, maxToken int) (nOffset int, ntokens []token)

func lz77Asm32kL15V3(base *level2context, input []byte, processed int, offset int, tokens []token, maxToken int) (nOffset int, ntokens []token)

func lz77Asm4kL15V4(base *level2context, input []byte, processed int, offset int, tokens []token, maxToken int) (nOffset int, ntokens []token)

func lz77Asm32kL15V4(base *level2context, input []byte, processed int, offset int, tokens []token, maxToken int) (nOffset int, ntokens []token)
